#!/usr/bin/env python3
"""Build data/index.json: one entry per card (id, issuer, name, path to the raw card file).

Clients (including the chat bot) read this single file instead of listing data/cards/ through the
GitHub API, which rate-limits unauthenticated callers. The output is deterministic (sorted by id, no
timestamps) so scripts/validate.py can fail when it is out of date.

`path` is relative to the repository root. The raw URL of a card is the raw base of the `main`
branch plus `path`, i.e. the URL index.json was fetched from with `data/index.json` replaced by
`path`. The repository owner is deliberately not written into this file: owner handles are on the
repo's privacy deny-list (scripts/scan_repo.py).

Usage:
  python scripts/build_index.py           # (re)write data/index.json
  python scripts/build_index.py --check   # exit 1 if data/index.json is missing or stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sgcards_lib import ROOT, card_files, load_yaml  # noqa: E402

INDEX_FILE = ROOT / "data" / "index.json"


def build_index(cards_dir=None) -> str:
    cards = []
    for path in card_files(cards_dir):
        doc = load_yaml(path)
        cards.append({
            "id": doc.get("id") or path.stem,
            "issuer": doc.get("issuer"),
            "name": doc.get("name"),
            "path": f"data/cards/{path.name}",
        })
    cards.sort(key=lambda c: c["id"])
    index = {
        "description": "Card list for sg-cards-data. Generated by scripts/build_index.py; do not edit by hand.",
        "paths": "relative to the repository root; raw URL = raw base of the main branch + path "
                 "(the URL this file was fetched from, with data/index.json replaced by path)",
        "count": len(cards),
        "cards": cards,
    }
    return json.dumps(index, indent=1, ensure_ascii=False) + "\n"


def index_is_current() -> bool:
    return INDEX_FILE.exists() and INDEX_FILE.read_text() == build_index()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="only check that data/index.json is up to date")
    args = ap.parse_args()
    if args.check:
        if index_is_current():
            print("data/index.json is up to date")
            return 0
        print("data/index.json is missing or out of date: run python scripts/build_index.py")
        return 1
    INDEX_FILE.write_text(build_index())
    print(f"wrote {INDEX_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
